### PR TITLE
Bugfix: Don't break when encountering unknown keys in g-stream

### PR DESCRIPTION
**Pull request by sognetic**
Hi,
this is almost a bit small for a PR but some (not all for some reason) packets in the JSON g-stream contain an attribute called `'n_cks_errs'`. These seem to be checksum errors and of course lead to an error as I didn't know about this keyword. I've now added the attribute. I've also added `**kwargs` so additional keywords (which I don't know about) don't break everything again. These are not used so far as any dynamic solutions are somewhat unsatisfactory. Let me know what you think, I can of course implement some dynamic storage of these possible additional values in a dict or similar.

I'd also like to at least notify users about additional values in the stream but that seems to be difficult without some kind of logging state as I don't want to spam prints for every packet.

### CODE REVIEW

**Review by maxfischer2781 — CHANGES_REQUESTED** [review]
I'm fine with not dumping the ``**kwargs`` into some dynamic storage, but you are right that just silently dropping them isn't ideal either.

My proposal is to add a literal warning using [the ``warnings`` module](https://docs.python.org/3/library/warnings.html). You could use a setup like this:
```python3
import warnings
...

# inside __init__
        if kwargs:
            warnings.warn(
                f"{self.__class__.__name__} ignored {kwargs}",
                category=RuntimeWarning
            )
```
This should be very fast in the normal case and ``warnings`` will emit the message only once by default.

**Comment by sognetic** [comment]
Ok, I've done that, thanks for the suggestion!. The only disadvantage I see with that solution is that it doesn't trigger warnings if further additional attributes are encountered after the first missing attribute already triggers a warning. But I guess this is not too bad.

**Comment by maxfischer2781** [comment]
I just gave this a test-run, the warning filter is per message *text* – since ``kwargs`` are formatted into the message, different ``kwargs`` trigger the warning again.

**Review by maxfischer2781 — APPROVED** [review]
Thanks for the adjustment! Looks good to me.

**Comment by sognetic** [comment]
> I just gave this a test-run, the warning filter is per message _text_ – since `kwargs` are formatted into the message, different `kwargs` trigger the warning again.

I tested it too but just noticed that I made a mistake in my test which gave me only a single message. Good thing it works, sorry for the noise.

**Pull request merged**
